services:
    postgres:
        image: postgres
        volumes:
            - ./data/postgres:/var/lib/postgresql/data
        restart: always
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: root
        ports:
            - '5432:5432'

networks:
    default:
        name: local-network
        external: true
